FROM alpine:latest

ENV SCRIPT_PATH=/attack.sh
ENV WORDLIST_PATH=/password.txt

RUN apk add --no-cache curl bash

COPY attack.sh ${SCRIPT_PATH}
COPY password.txt ${WORDLIST_PATH}

RUN chmod +x ${SCRIPT_PATH}

CMD ["/attack.sh"]
